### ISSUE TITLE
Incorrect usage of datetime.now(UTC)

### ISSUE THREAD

**Issue by balagrivine** [tyball21/Open-HAMS#9]
I am encountering an issue while running the migration script to create a database while setting up the project.
This piece of code imports UTC from datetime, yet UTC is not a standalone object in datetime:

from datetime import UTC, datetime, timedelta
datetime.now(UTC)

I believe the correct way to use UTC is throgh the piece of code below:

from datetime import timezone
datetime.now(timezone.utc)

This approach correctly creates a datetime object representing the current time in UTC.

**Comment by ahmedivy** [comment]
We are using python 3.12 for this project, and datetime.UTC is an alias for timezone.utc (added in Python 3.11).

**Comment by ahmedivy** [comment]
As mentioned in [docs](https://docs.python.org/3/library/datetime.html#datetime.UTC)
